spring:
  application:
    name: lolweb
  main:
    banner-mode: console
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: detect
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    static-path-pattern: "/static/**"
  servlet:
    multipart:
      enabled: true # Whether to enable support of multipart uploads.
      max-file-size: 100MB # single file size
      max-request-size: 100MB # total uploaded data size
  thymeleaf:
    prefix: classpath:/config/templates/
    suffix: .html
  security:
    user:
      name: user
      password: 1234
  web:
    resources:
      add-mappings: true
  datasource:
    hikari:
      idle-timeout: 10000
      max-lifetime: 27000
      connection-timeout: 10000
      validation-timeout: 10000
      leak-detection-threshold: 2000
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/lol_db
    username: user
    password: user1234
server:
  port: 8080
  servlet:
    context-path: /lol
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 30m
      persistent: true
  error:
    whitelabel:
      enabled: false
logging:
  level:
    root: INFO
    sql-logging: DEBUG
    org.springframework: INFO
    com.standard.common: DEBUG
    com.standard.lolweb: DEBUG
    web: DEBUG
mybatis:
  mapper-locations: classpath*:config/mapper/*.xml,
    classpath*:config/mapper/**/*.xml
  type-aliases-package: com.standard.lolweb.model
  executor-type: BATCH
  configuration:
    cache-enabled: true
    use-generated-keys: true
    lazy-loading-enabled: true
    use-column-label: true
    auto-mapping-behavior: PARTIAL
    multiple-result-sets-enabled: true
    safe-row-bounds-enabled: true
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,beans,httpexchanges
global:
  api:
    key: RGAPI-47ef6153-e8e5-4f14-8050-5251489178b3